### ISSUE TITLE
Update to Lumen 5.4

### ISSUE THREAD

**Issue by evicent** [akaita/json-web-token-authentication-for-lumen-5#1]
Hi,

First of all: Thank you!

I have a project with Lumen 5.4, and I can't install because of the dependency (Lumen 5.3). Any chance to upgrade?

Regards

**Comment by akaita** [comment]
@evicent Thank you for your feedback!

I used this very [same procedure](http://www.akaita.com/post/json-web-token-authentication-for-lumen-5-tymon-jwt-auth) to create a Lumen 5.4 project not long ago. Everything worked perfectly fine.

As of now you could just upgrade this project to Lumen 5.4 or manually change the dependency (if you are doing some copy&paste from this project to yours).

I will try to upgrade this project to Lumen 5.4, but sincerely it won't be my main priority... could you give a try to the instructions or [just upgrade the project ](https://lumen.laravel.com/docs/5.4/upgrade#upgrade-5.4.0)? I'm sure it won't give you any trouble. Otherwise please feel free to come back around :)

**Comment by akaita** [comment]
Lumen is now on version 5.5 and I won't be spending time on this every time they upgrade. 
Ping me if it stops working. I will otherwise assume it works ok.

**Comment by evicent** [comment]
Oh.  Thank you very much!!!

Regards
